forms/calendar.py
from datetime import datetime
from flask_wtf import FlaskForm
from wtforms import DateField, HiddenField, SelectField, StringField, BooleanField, SubmitField, IntegerField
from wtforms.validators import DataRequired

class CalendarForm(FlaskForm):
    year = HiddenField('year')
    month = HiddenField('month')

routes/calendars.py
import calendar
from datetime import datetime
from flask import Blueprint, flash, redirect, render_template, request, url_for
from database.models.timesheet import Timesheet
from forms.calendar import CalendarForm
from routes.customHTMLCalendar import CustomHTMLCalendar

calendars_route = Blueprint('calendars', __name__)

@calendars_route.route('/', methods=['GET', 'POST'])
@calendars_route.route('/<int:year>/<int:month>', methods=['GET', 'POST'])
def index(year=None, month=None, day=None):
    # Get current year and month    
    now = datetime.now()    
    print("Aqui:", month, year)
    if year:                
        print("Aqui2:", month, year)
    else:
        year = request.args.get('year', now.year, type=int)
        month = request.args.get('month', now.month, type=int)            

    form = CalendarForm(year=year, month=month)

    if form.validate_on_submit():
        year=int(form.year.data)
        month=int(form.month.data)
        print("aqui3:", month, year)

    # Create a calendar
    cal = CustomHTMLCalendar(calendar.SUNDAY)
    cal_html = cal.formatmonth(year, month)    

    # Navigation links
    print("aqui4:", month, year)
    prev_month = month - 1 if month > 1 else 12
    prev_year = year if month > 1 else year - 1
    next_month = month + 1 if month < 12 else 1
    next_year = year if month < 12 else year + 1

    return render_template('calendar_form.html', cal_html=cal_html, form=form, prev_year=prev_year, prev_month=prev_month, next_year=next_year, next_month=next_month)

@calendars_route.route('/day/<int:year>/<int:month>/<int:day>')
def day_view(year, month, day):
    # Handle the day view here
    return redirect(url_for('timesheets.day', year=year, month=month, day=day))
    #return f"Details for {year}-{month}-{day}"

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

routes/project_tasks.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from database.DTO.project_tasksDTO import ProjectTasksDTO
from database.models.project import Project
from database.models.project_tasks import ProjectTasks
from database.models.subtask import Subtask
from database.models.task import Task
from forms.project_task import ProjectTasksForm
from forms.project import ProjectForm

project_tasks_route = Blueprint('project_tasks', __name__)

@project_tasks_route.route('/<int:id>/')
def index(id):    
    project = Project.get_by_id(id)
    if project == None:
        flash('Project not found','error')

    form = ProjectTasksForm()
    form.tasks.choices = [(task.id, task.task_name) for task in Task.getAll()]
    form.projectId.data = project.id    
    project_tasks = project_tasks_DTO(
                        ProjectTasks.get_by_project_id(project.id)                        
    )
    
    for task in project_tasks:
        print(task)

    return render_template('project_tasks_form.html', project_tasks=project_tasks, form=form, project=project)

@project_tasks_route.route('/save', methods=['POST'])
def save():    
    form = ProjectTasksForm()       

    if form.validate_on_submit():      
        project_task = ProjectTasks.get_by_project_id_task_id(form.projectId.data, 
                                                              form.tasks.data        
        )
        if project_task:
            flash('Task already exist in this Project', "warning")    
        else:
            new_projectTask = ProjectTasks(project_id = form.projectId.data, 
                                           status = "Enabled", 
                                           task_id = form.tasks.data)
            new_projectTask.add()                            
            flash('Project Task created:', "success")
    else:
        print("Form is not valid")
        for fieldName, field in form.errors.items():
            print(f"Error in {fieldName}: {field}")
        flash('Error creating Project Task', "error")
        
        #id=form.projectId.data
    return redirect(url_for('project_tasks.index', id=form.projectId.data))
    
@project_tasks_route.route('/disable/<int:id>')
def disable(id):    
    project_tasks = ProjectTasks.get_by_id(id)
    project_tasks.set_status()    
    return redirect(url_for('project_tasks.index', id=project_tasks.project_id))


@project_tasks_route.route('/delete')
def delete():
    pass

def project_tasks_DTO(pts):   
    project_tasks_dto = [ProjectTasksDTO(pt) for pt in pts]
    return project_tasks_dto

routes/projects.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from database.models.project import Project, Project2
from forms.project import ProjectForm

projects_route = Blueprint('projects', __name__)

@projects_route.route('/')
def index():
    projects = Project.getAll()
    print(projects)
    form = ProjectForm()
    return render_template('project_form.html', projects=projects, form = form)

@projects_route.route('/save', methods=['POST'])
def save():    
    form = ProjectForm()              
    id = form.id.data
    if form.validate_on_submit(): 
        if id:
            project = Project.get_by_id(id)
            if project:            
                project.projectCode = form.projectCode.data
                project.projectName = form.projectName.data               
                project.status = form.projectStatus.data                
                project.update()
            else:
                flash('Project not found', "error")
        else:
            new_project = Project(projectCode=form.projectCode.data, 
                                  projectName=form.projectName.data,
                                  status = form.projectStatus.data)    

            new_project.add()                    
            flash('Project created', "success")
        return redirect(url_for('projects.index'))
    
@projects_route.route('/edit/<int:id>')
def edit(id):
    projects = Project.getAll()   
    project = Project.get_by_id(id)
    form = ProjectForm(obj=project)             
    return render_template('project_form.html', projects=projects, form=form)

@projects_route.route('/delete')
def delete():
    pass

routes/subtasks.py
from flask import Blueprint, render_template
from database.models.subtask import Subtask
from database.models.task import Task
from database.DTO.subtaskDTO import SubtaskDTO

subtasks_route = Blueprint('subtasks', __name__)

@subtasks_route.route('/')
def getSubtasks():
    subtasks = Subtask.getAll()
    subtasks_return = []

    for s in subtasks:
        s_dto = SubtaskDTO(s.id,
                           s.subtask,
                           Task.get(Task.id == s.task).task,
                           s.status
                           )
        subtasks_return.append(s_dto)
                
    return render_template('subtask.html', subtasks = subtasks_return)

routes/tasks.py
from flask import Blueprint, render_template
from database.models.task import Task

tasks_route = Blueprint('tasks', __name__)

@tasks_route.route('/')
def getTasks():
    tasks = Task.select()
    return render_template('task.html', tasks = tasks)

routes/timesheets.py
from flask import Blueprint, flash, jsonify, redirect, render_template, request, url_for
from database.DTO.timesheetDTO import TimesheetDTO
from database.models.project_tasks import ProjectTasks
from database.models.task import Task
from database.models.timesheet import Timesheet
from database.models.project import Project
from database.models.subtask import Subtask
from forms.timesheet import TimeSheetForm
from database.models.timesheet_status import TimesheetStatus
from peewee import fn
from datetime import datetime

timesheets_route = Blueprint('timesheets', __name__)

@timesheets_route.route('/')
@timesheets_route.route('/<int:id>')
@timesheets_route.route('/<int:year>/<int:month>/<int:day>')
def index(id=None, year=None, month=None, day=None):         
    
    if year:
        timesheet_day_selected = f'{year}-{month:02d}-{day:02d}'        
        form = TimeSheetForm()        
        form.timesheet_date.data = timesheet_day_selected

        #Fetch timesheet records        
        timesheets = timesheetsDTO(
            Timesheet.select().where(
                (Timesheet.status != 'Deleted') &
                (Timesheet.timesheet_date == timesheet_day_selected)
            )
        )        

        #Fetch timesheet status
        timesheet_status = TimesheetStatus.select().where(
                    (TimesheetStatus.operator == "m.leite@fugro.com") &
                    (TimesheetStatus.timesheet_date == timesheet_day_selected)
        ).first()

        if timesheet_status:    
            print(timesheet_status.status)
            form.status.data = timesheet_status.status
        else:
            timesheet_status = TimesheetStatus(operator = "m.leite@fugro.com",
                                               status = "Open",
                                               timesheet_date = timesheet_day_selected
                                    )
            timesheet_status.save()
            print("Create timesheetstatus")
        form.status.data = timesheet_status.status
    else:
        flash('Timesheet date not informed')

    if id:
        form = TimeSheetForm(obj=Timesheet.get_by_id(id))                        
    #else:
        #form = TimeSheetForm(timesheet_date = timesheet_day_selected)
     #   print("ddddxxxx")
    
    projects = Project.select().where(Project.status != "disabled")
        
    form.projects.choices = [("", "Select a project")] + [(p.id, p.projectName) for p in Project.select().where(Project.status != "disabled")]
    
    #form.projects.choices = [(p.id, p.projectName) for p in Project.select().where(Project.status != "disabled")]

    return render_template('timesheet_form.html', timesheets=timesheets, projects=projects, form=form, year=year, month=month, day=day, timesheet_day_selected=convert_date_ymd_to_mdy(year, month, day))

#@timesheets_route.route('/save', methods=['POST'])
@timesheets_route.route('/save/<int:year>/<int:month>/<int:day>', methods=['POST'])
def save(year, month, day):     
    print("Aqui")

    form = TimeSheetForm()
    if request.method == 'POST':
        print("Aqui2")

        if form.validate_on_submit():
            print("Aqui3", form.projects.data)
            id = form.id.data
            if id:
                timesheet = Timesheet.get_by_id(id)
                if timesheet:
                    # Update the timesheet with form data
                    timesheet.operator = form.operator.data
                    timesheet.timesheet_date = form.timesheet_date.data
                    timesheet.projectId = form.projects.data
                    #timesheet.tasks = form.tasks.data
                    timesheet.sub_taskId = form.sub_tasks.data
                    timesheet.unit_name = form.unit_name.data
                    timesheet.sub_unit_name = form.sub_unit_name.data
                    timesheet.start_chainage = form.start_chainage.data
                    timesheet.end_chainage = form.end_chainage.data
                    timesheet.task_status = form.task_status.data
                    timesheet.type_feature = form.type_feature.data
                    timesheet.type_task = form.type_task.data
                    timesheet.comments = form.comments.data
                    timesheet.start_time = form.start_time.data
                    timesheet.end_time = form.end_time.data
                    timesheet.status = form.status.data
                    timesheet.save()                    
                    flash('Timesheet updated successfully', 'success')
                else:
                    flash('Timesheet not found', 'error')
            else:
                print("Aqui:", form.sub_tasks.data)
                # Create a new timesheet
                new_timesheet = Timesheet(
                    operator=form.operator.data,
                    timesheet_date=form.timesheet_date.data,
                    projectId = form.projects.data,                                        
                    #tasks=form.tasks.data,
                    sub_taskId=form.sub_tasks.data,
                    unit_name=form.unit_name.data,
                    sub_unit_name=form.sub_unit_name.data,
                    start_chainage=form.start_chainage.data,
                    end_chainage=form.end_chainage.data,
                    task_status=form.task_status.data,
                    type_feature=form.type_feature.data,
                    type_task=form.type_task.data,
                    comments=form.comments.data,
                    start_time=form.start_time.data,
                    end_time=form.end_time.data,
                    status="Open"
                )
                new_timesheet.save()
                #return {jsonify(new_timesheet)}
                flash('Timesheet created successfully', 'success')
        else:            
           for field, errors in form.errors.items():
            for error in errors:
                flash(f"Error in {getattr(form, field).label.text}: {error}", "error")
                
    
    
    return redirect(url_for('timesheets.index', year=year, month=month, day=day))
    
@timesheets_route.route('/edit/<int:id>', methods=['POST'])
def edit(id):        
    timesheet = Timesheet.get_by_id(id)
    if timesheet:
        year = timesheet.timesheet_date.year
        month = timesheet.timesheet_date.month
        day = timesheet.timesheet_date.day                               
    else:
        flash('Timesheet not found', 'error')

    return redirect(url_for('timesheets.index', id=id, year=year, month=month, day=day))

#@timesheets_route.route('/delete/<int:id>/<int:year>/<int:month>/<int:day>', methods=['POST'])
#def delete(id, year, month, day):    
@timesheets_route.route('/delete/<int:id>/')
def delete(id):    
    timesheet = Timesheet.get_by_id(id)    
    if timesheet:        
        year = timesheet.timesheet_date.year
        month = timesheet.timesheet_date.month
        day = timesheet.timesheet_date.day        
        timesheet.status = "Deleted"
        timesheet.save()
        flash('Timesheet deleted successfully')
    else:
        flash('Timesheet not found')
    return redirect(url_for('timesheets.index', year=year, month=month, day=day))

@timesheets_route.route('/tasks/<int:projectId>/')
def task(projectId):
    print("A:", projectId)
    tasksquery = ProjectTasks().select().where(ProjectTasks.projectId == projectId)

    tasks = []

    for t in tasksquery:
        task = Task.get_by_id(t.id)
        taskDTO = {}
        taskDTO['id'] = task.id
        taskDTO['task'] = task.task
        tasks.append(taskDTO)

    return jsonify({'tasks': tasks})

@timesheets_route.route('/subtasks/<int:taskId>/')
def subtask(taskId):
    print("B:", taskId)
    subtasksquery = Subtask().select().where(Subtask.task == taskId)

    subtasks = []

    for t in subtasksquery:
        print(t.id)
        subtask = SubTask.get_by_id(t.id)
        
        subtaskDTO = {}
        subtaskDTO['id'] = subtask.id
        subtaskDTO['subtask'] = subtask.subtask
        print(subtaskDTO)
        subtasks.append(subtaskDTO)

    return jsonify({'tasks': subtasks})

@timesheets_route.route('/submit/<int:year>/<int:month>/<int:day>')
def submit(year, month, day):
    form = TimeSheetForm()

    timesheet_status = TimesheetStatus.select().where(TimesheetStatus.timesheet_date  == convert_date_ymd_to_date(year, month, day),
                                                          TimesheetStatus.operator == "m.leite@fugro.com").first()
    
    if timesheet_status:                  
        print("XX", timesheet_status.status) 
        if timesheet_status.status == "Approved":
            flash("Timesheet already approved! No changes are allowed.", "error")
        else:
            if timesheet_status.status == "Open":
                new_status = "Submitted"
            else:
                new_status = "Open"
                print("Reopening")            
            
            timesheet_status.status = new_status
            timesheet_status.save()

            #Update timesheet records        
            query = Timesheet.update(status=new_status).where(
                Timesheet.timesheet_date == convert_date_ymd_to_date(year, month, day),
                Timesheet.status != 'Deleted'
                )        
            query.execute()
            print("KKKK:", timesheet_status.status)
    else:
        flash("Timesheet status not found", "error")
                                                          
    form.status.data = new_status
    print("KSKSK:", form.status.data)
        
    return redirect(url_for('timesheets.index', year=year, month=month, day=day))


def convert_date_ymd_to_mdy(year, month, day):
    date_obj= datetime(year, month, day)
    return date_obj.strftime('%m-%d-%Y')

def convert_date_ymd_to_date(year, month, day):
    # Format the date as "YYYY-MM-DD"
    formatted_date = f'{year:04d}-{month:02d}-{day:02d}'

templates/calendar_form.html
{% extends "index.html" %}
{% block title %}Calendar{% endblock %}

{% block content %}
<h1>Calendar</h1>
    <button class="action-btn">
        <a href="{{ url_for('calendars.index', year=next_year, month=next_month) }}">
            <span class="material-icons">arrow_forward</span>
        </a>                            
    </button>    
    <button class="action-btn">
        <a href="{{ url_for('calendars.index', month=prev_month) }}">
            <span class="material-icons">arrow_back</span>
        </a>                            
    </button>
    <div class="calendar-table">{{ cal_html|safe }}</div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block head %}
    <title>{% block title %}{% endblock %}</title>  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Time Builder</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet">

    {% endblock %}
</head>
<body>
    <div class="d-flex">
        <div class="sidebar" id="sidebarMenu">
            <div class="d-flex align-items-center mb-3">
                <img src="/static/images/logo-fugro.png" alt="Logo" class="mr-2" id="logo">
            </div>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('home.home') }}">
                        <span class="material-icons">home</span>
                        <span class="text">Home</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#settingsSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <span class="material-icons">settings</span>
                        <span class="text">Settings</span>
                    </a>
                    <ul class="collapse list-unstyled" id="settingsSubmenu">
                        <li class="nav-item sub-item">
                            <a class="nav-link" href="{{ url_for('projects.index') }}">
                                <span class="material-icons">build</span>
                                <span class="text">Projects</span>
                            </a>
                        </li>
                        <li class="nav-item sub-item">
                            <a class="nav-link" href="{{ url_for('tasks.getTasks') }}">
                                <span class="material-icons">assignment</span>
                                <span class="text">Tasks</span>
                            </a>
                        </li>
                        <li class="nav-item sub-item">
                            <a class="nav-link" href="{{ url_for('subtasks.getSubtasks') }}"> 
                                <span class="material-icons">subdirectory_arrow_right</span>
                                <span class="text">Sub-tasks</span>
                            </a>
                        </li>
                        <li class="nav-item sub-item">
                            <a class="nav-link" href="#">
                                <span class="material-icons">people</span>
                                <span class="text">Operators</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link"  href="{{ url_for('calendars.index') }}">
                    <span class="material-icons">schedule</span>
                    <span class="text">Timesheet</span>
                  </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <span class="material-icons">check_circle</span>
                        <span class="text">Approval</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <span class="material-icons">assessment</span>
                        <span class="text">Reports</span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="content main-content mt-3">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    {% if category == "success" %}
                    <div class="alert alert-success alert-toster mb-3" role="alert" id="autoDismissAlert">
                        {{ category }}: {{ message }}                        
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}
                    {% if category == "warning" %}
                    <div class="alert alert-warning alert-toster mb-3" role="alert" id="autoDismissAlert">
                        {{ category }}: {{ message }}                        
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}
                    {% if category == "error" %}
                    <div class="alert alert-danger alert-toster mb-3" role="alert" id="autoDismissAlert">
                        {{ category }}: {{ message }}                        
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            {% endwith %}
            {% block content %}
            <div class="topbar">
                <h5>Time Builder</h5>
                <p>A simple timesheet app</p>                
            </div>
            {% endblock %}
        </div>

        <div class="footer">
          {% block footer %}            
          {% endblock %}
          </div>
       </div>
    </div>
    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
 
    <script>
        document.getElementById('logo').addEventListener('click', function() {
            document.getElementById('sidebarMenu').classList.toggle('collapsed');
        });
    </script>    
    <script>
        // Wait for the DOM to be fully loaded
        document.addEventListener("DOMContentLoaded", function() {
            // Set a timeout to hide the alert after 3 seconds (3000 milliseconds)
            setTimeout(function() {
                var alertElement = document.getElementById("autoDismissAlert");
                if (alertElement) {
                    alertElement.style.display = "none";
                }
            }, 3000);
        });
    </script>
</body>
</html>

templates/project_form.html
{% extends "index.html" %}
{% block title %}Project{% endblock %}

{% block content %}
<div class="container mt-3">
    <h2>Projects</h2>    
    <form id="projectForm" method="POST" action="{{ url_for('projects.save', id=form.id.data) }}">                
        {{ form.hidden_tag() }}                
        <div class="form-row align-items-end">
            <div class="form-group col-md-3">
                <label for="projectCode">Project Code</label>                                
                {{ form.id }}
                {{ form.projectCode }}
            </div>
            <div class="form-group col-md-3">
                <label for="projectName">Project Name</label>                                
                {{ form.projectName }}
            </div>
            <div class="form-group col-md-2">
                <label for="projectName">Status</label>                                
                {{ form.projectStatus }}
            </div>
            <div class="form-group col-md-2">
                <button type="submit" class="submit-btn">
                    <span class="material-icons">add</span>
                </button>
            </div>            
        </div>
    </form>
    
    <!-- Grid to display projects -->
    <table class="table table-bordered-rows mt-3">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Project Code</th>
                <th scope="col">Project Name</th>
                <th scope="col">Status</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody id="projectTableBody">
            {% for project in projects %}
                <tr>
                    <td>{{ project.id }}</td>                    
                    <td>{{ project.projectCode }}</td>
                    <td>{{ project.projectName }}</td>
                    <td>{{ project.status }}</td>
                    <td>
                        <button class="action-btn">
                            <a href="{{ url_for('project_tasks.index', id=project.id) }}">
                                <span class="material-icons">list</span>
                            </a>                            
                        </button>
                        <button class="action-btn">
                            <a href="{{ url_for('projects.edit', id=project.id) }}">
                                <span class="material-icons">edit</span>
                            </a>                            
                        </button>
                        <button class="action-btn">
                            <a href="{{ url_for('projects.delete', id=project.id) }}">
                                <span class="material-icons">delete</span>
                            </a>
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}     



    
    

templates/project_tasks_form.html
{% extends "index.html" %}
{% block title %}Project Tasks{% endblock %}

{% block content %}
<div class="container mt-3">
    <div>
        <button class="action-btn">
            <a href="{{ url_for('projects.index') }}">
                <span class="material-icons">calendar_today</span>
            </a>                            
        </button>    
    </div>
    <h2>Project Tasks</h2>    
    <div>
        Project: {{ form.projectId }} {{ project.projectCode }} - {{ project.projectName }}
        <P>
    </div>
    <form id="projecTasksForm" method="POST" action="{{ url_for('project_tasks.save', id=form.id.data, projectId=form.projectId.data) }}">                
        {{ form.hidden_tag() }}                                
        {{ form.status }}
        <div class="form-row align-items-end">
            <div class="form-group col-md-8">
                <label for="projectCode">Task</label>                                
                {{ form.id }}       
                {{ form.projectId }}         
                {{ form.tasks }}
            </div>
            <div class="form-group col-md-4">
                <button type="submit" class="submit-btn">
                    <span class="material-icons">add</span>
                </button>
            </div>            
        </div>
    </form>
    
    <!-- Grid to display projects -->
    <table class="table table-bordered-rows mt-3">
        <thead>
            <tr>
                <th scope="col">Id</th>                
                <th scope="col">Task</th>
                <th scope="col">Status</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody id="projectTableBody">
            {% for p in project_tasks %}
                <tr>                    
                    <td>{{ p.id }}</td>                    
                    <td>{{ p.task }}</td>                                        
                    <td>{{ p.status }}</td>
                    <td>
                        <button class="action-btn">
                            <a href="{{ url_for('project_tasks.disable', id=p.id) }}">
                                <span class="material-icons">edit</span>
                            </a>                            
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}     



    
    